"""Build curated frontier evidence/model records from checked official snapshots.

Facts below are editorial annotations, not automatically inferred from model names.
The frozen upstream cards, reports, configs and source files are in research/frontier.
"""
import json,pathlib
ROOT=pathlib.Path(__file__).resolve().parents[1];FR=ROOT/'research/frontier';DATE='2026-09-22';S=[];M=[]
def card(id,repo,title,supports,chapters,license=None):
 f=FR/repo.replace('/','--');m=json.loads((f/'metadata.json').read_text());sha=m['sha'];lic=license or m.get('cardData',{}).get('license','未核验')
 s=dict(id=id,title=title,organization=repo.split('/')[0],type='模型卡',url=f'https://huggingface.co/{repo}/blob/{sha}/README.md',published='未标注',accessed=DATE,repository='https://huggingface.co/'+repo,version=sha,license=lic,supports=supports,chapters=chapters,evidence='官方事实',file='README.md',localPath=str((f/'README.md').relative_to(ROOT)),rawUrl=f'https://huggingface.co/{repo}/resolve/{sha}/README.md',notes='固定官方模型卡；HF首次建仓时间为 '+str(m.get('createdAt'))+'，不能自动等同于正式发布日期。性能数字是作者报告，未在本课程独立重跑。')
 S.append(s);return s

def report(id,parent,file,title,supports,github=False):
 c=next(s for s in S if s['id']==parent);folder=(ROOT/c['localPath']).parent
 if github:
  a=json.loads((folder/'github-report-audit.json').read_text());repo='https://github.com/'+a['repository'];sha=a['sha'];url=f"{repo}/blob/{sha}/{file}";raw=a['url']
 else:repo=c['repository'];sha=c['version'];url=f'{repo}/resolve/{sha}/{file}';raw=url
 s=dict(id=id,title=title,organization=c['organization'],type='技术报告',url=url,published='未标注',accessed=DATE,repository=repo,version=sha,license='报告未单独标注；不自动继承权重许可证',supports=supports,chapters=c['chapters'],evidence='论文实验',file=file,localPath=str((folder/file).relative_to(ROOT)),rawUrl=raw,notes='完整官方PDF已下载并用pypdf提取文本；核验关键章节，未复现所报告的大规模训练。')
 S.append(s)
def code(id,parent,file,symbol,line,n,title,supports,call,io,license=None):
 c=next(s for s in S if s['id']==parent);folder=(ROOT/c['localPath']).parent;path=folder/file;text=path.read_text();lines=text.splitlines()
 s=dict(id=id,title=title,organization=c['organization'],type='官方源码',url=f"{c['repository']}/blob/{c['version']}/{file}#L{line}",published='未标注',accessed=DATE,repository=c['repository'],version=c['version'],license=license or c['license'],supports=supports,chapters=c['chapters'],evidence='源码观察',file=file,symbol=symbol,localPath=str(path.relative_to(ROOT)),rawUrl=f"{c['repository']}/resolve/{c['version']}/{file}",excerpt='\n'.join(lines[line-1:line-1+n]),excerptStart=line,callChain=call,inputOutput=io,notes='官方模型定义／推理实现；此文件能前向或计算loss，不等于发布了生成该checkpoint的完整预训练与RL流水线。')
 S.append(s)
def model(id,name,org,current,generations,takeaway,changes,questions,limits,disclosure,sourceIds,chapters):
 M.append(dict(id=id,name=name,organization=org,current=current,generations=generations,takeaway=takeaway,changes=changes,questions=questions,limits=limits,disclosure=disclosure,sourceIds=sourceIds,chapters=chapters,reported=DATE))
card('deepseek-v41','deepseek-ai/DeepSeek-V4.1-Flash','DeepSeek-V4.1-Flash：官方模型卡',['CED与CSA2的结构说明','45T多模态预训练；SFT→RL→OPD与Agent数据环境建设','评测harness、上下文与采样预算'],['frontier-reading','modern-pretraining','posttraining','agent-flywheel','evaluation','inference-serving'],'MIT（仓库LICENSE）')
report('deepseek-v41-report','deepseek-v41','DeepSeek_V41_Tech_Report.pdf','DeepSeek-V4.1 Technical Report',['§2.2 CED；§2.3 CSA2缓存与索引共享','§2.3.2 首个indexer全范围检索，后续受候选池约束；在后训练引入','§4预训练与§5数据/环境导向后训练'])
code('deepseek-v41-code','deepseek-v41','inference/model.py','Attention._compress_kv / Transformer.forward',739,10,'DeepSeek-V4.1：共享压缩KV的真实推理调用链',['source layer计算压缩KV，其他层读shared cache','forward受torch.inference_mode装饰，不能冒充完整训练器'],'generate.py → Transformer.forward → Block.forward → Attention.forward → _compress_kv/_compress_topk_idxs','input_ids [B,S]及可选图像→隐藏状态与共享KV；forward返回output_ids、logits、main_hidden。')
card('kimi-k3','moonshotai/Kimi-K3','Kimi K3：原生多模态与混合注意力',['KDA与Gated MLA混合、Attention Residuals、Stable LatentMoE','公开权重及1M上下文设计'],'frontier-reading long-context moe-training posttraining agent-rollout'.split(),'Kimi K3 License（自定义许可证）')
report('kimi-k3-report','kimi-k3','k3_tech_report.pdf','Kimi K3: Open Frontier Intelligence',['§2 KDA、AttnRes与latent MoE','§3联合图文训练及cooldown长上下文curriculum','§4 SFT→领域RL→多教师on-policy distillation；§5系统设计'],True)
code('kimi-k3-code','kimi-k3','modeling_kimi_linear.py','_apply_attn_res / KimiDeltaAttention.forward',1075,14,'Kimi K3：Attention Residuals与KDA模式分派',['_apply_attn_res在深度候选上softmax并加权求和','KDA训练使用chunk模式，单token缓存解码用fused_recurrent'],'KimiLinearModel → KimiDecoderLayer._forward_attn_residual → _apply_attn_res；self_attn → KimiDeltaAttention.forward → chunk_kda/fused_recurrent_kda','prefix_sum [T,H]、block_residual [T,N,H]→输出[T,H]；KDA输入[B,S,H]并更新recurrent cache。','Kimi K3 License；文件头标明继承的DeepSeek部分为Apache-2.0')
code('kimi-k3-vision-code','kimi-k3','modeling_kimi_k3.py','KimiK3ForConditionalGeneration',893,10,'Kimi K3：视觉输入与语言模型的接口',['视觉塔/projector接入KimiLinearForCausalLM，不是RL训练器'],'KimiK3ForConditionalGeneration → vision_tower/mm_projector → language_model','图像patch与文本token→投影视觉表示和条件语言建模输出。','Kimi K3 License；文件头明确llava继承部分为Apache-2.0')
card('qwen38','Qwen/Qwen3.8-Flash-Next','Qwen3.8-Flash-Next：QSA、Gated Residual与训练配方',['QSA按micro-block稀疏选择；与Gated DeltaNet混合','Gated Residual使用element-wise read gate与scalar write gate','Muon/AdamW按参数组分配；本版本为实验架构预览'],'frontier-reading modern-pretraining training-stability compute-budget long-context'.split(),'Qwen Community License 1.0（自定义）')
report('qwen38-report','qwen38','tech_report.pdf','Qwen3.8-Flash-Next Technical Report',['残差分支稀疏化在预训练指标与后训练生成上的不一致','矩阵参数、router、embedding等优化器选择有区别','稀疏注意力、残差、embedding和kernel联合分析'],True)
card('qwen38-dense','Qwen/Qwen3.8-27B','Qwen3.8-27B：同代Dense混合架构对照',['Gated DeltaNet与Gated Attention的3:1层组成','本checkpoint为27B Dense；不同于Flash-Next的QSA/MoE/GR设计'],'frontier-reading modern-pretraining'.split(),'Apache-2.0（仓库LICENSE）')
card('glm53','zai-org/GLM-5.3','GLM-5.3：同一基础模型上的后训练变化',['官方声明与GLM-5.2使用同一base，变化来自post-training','模型卡公开多项harness、时限、采样及评测修订说明'],'frontier-reading posttraining evaluation agent-rewards'.split(),'GLM-5.3 License（自定义）')
S.append(dict(id='glm5-report',title='GLM-5: from Vibe Coding to Agentic Engineering',organization='Z.ai / GLM-5 Team',type='技术报告',url='https://arxiv.org/abs/2602.15763',published='2026-02-17',accessed=DATE,repository=None,version='arXiv:2602.15763',license='未核验',supports=['GLM-5家族公开训练研究；不能代表5.3版本所有改动已披露'],chapters=['frontier-reading'],evidence='论文实验',notes='5.3模型卡引用家族报告；本课不把家族早期报告冒充完整5.3配方。'))
card('mimo26','XiaomiMiMo/MiMo-V2.6-Flash-RL','MiMo-V2.6-Flash-RL：混合Agent RL与分组评分',['GRS与GAR区分通过测试的不同轨迹质量','多任务和多harness混合RL；MOPD2后续蒸馏'],'frontier-reading midtraining capability-shaping training-stability posttraining reasoning-rl agent-rewards agent-flywheel'.split(),'MIT（官方模型卡声明；仓库未列独立LICENSE文件）')
report('mimo26-report','mimo26','MiMo_V2_6_technical_report.pdf','MiMo-V2.6 Technical Report',['§3两段预训练与agent-centric mid-training','256K→1M、隐藏矩阵AdamW→Muown与MXFP4 QAT','§4.3 GRS离线rubric与GAR在线advantage redistribution'])
code('mimo26-code','mimo26','modeling_mimo_v2.py','MiMoV2ForCausalLM._get_multimodal_embeds',1758,12,'MiMo-V2.6：多模态embedding合并边界',['图像、视频、音频表示替换相应模态token位置','这是forward接口，不是报告中GRPO/GRS/GAR的训练实现'],'MiMoV2ForCausalLM.forward → _get_multimodal_embeds → visual/audio_encoder → MiMoV2Model','input_ids [B,S]、inputs_embeds [B,S,H]与模态数据→同shape混合embedding张量。','Apache-2.0（该源码文件头；区别于模型卡MIT）')
card('gemma4','google/gemma-4-12B-it','Gemma 4 12B Unified：面向本地部署的多模态路线',['12B unified encoder-free结构直接处理模态输入','Gemma4系列包含Dense/MoE与预训练/指令版本；版本级区别需单列'],'frontier-reading modern-pretraining inference-serving'.split(),'Apache-2.0（官方模型卡与Google许可证页确认）')
S.append(dict(id='gemma4-report',title='Gemma 4 Technical Report',organization='Gemma Team / Google DeepMind',type='技术报告',url='https://arxiv.org/abs/2607.02770v2',published='2026-07-02',accessed=DATE,repository=None,version='arXiv:2607.02770v2',license='未核验',supports=['Gemma4多种规模/架构与12B encoder-free多模态设计'],chapters=['frontier-reading','modern-pretraining'],evidence='论文实验',notes='v2发表于2026-07-24；本课仅依据所核验报告陈述，不把端侧模型当最大规模模型的替代结论。'))
shared={'Training Code':'本次发布材料未提供可复现全流程预训练器','Post-training Code':'报告／模型定义不等于完整RL训练流水线；未核验完整发布','Data Recipe':'方法级信息可读；完整可重建数据mixture未核验','API Only':'否；公开权重分支'}
model('deepseek','DeepSeek · V4.1-Flash','DeepSeek','本次核验代表：2026-09官方V4.1-Flash公开分支',['V3：MoE、MLA、FP8与MTP','V4.1-Flash：CED与CSA2，输入密集Agent成本设计'],'把训练架构与长期Agent输入、KV复用成本一起设计。',['CED改变decoder全局KV的来源；CSA2跨层复用缓存和索引','从文本效率配方走向原生图文联合训练','后训练报告把主要投入放在任务合成、环境规模与验证'],['压缩缓存后哪类长任务最先退步？','索引器成本究竟从哪个层开始不随全上下文线性增长？'],'没有复现报告的大规模训练；不能把前代超参数直接移植；官方benchmark采用特定harness与effort。',{**shared,'Open Weight':'是；本次核验官方权重与config','Open Source':'官方推理代码可读；训练全流程公开性单列','Inference Code':'inference/model.py、kernel.py等已定位','Technical Report':'固定HF SHA的完整PDF已核验','License':'MIT，见固定仓库LICENSE'},['deepseek-v41','deepseek-v41-report','deepseek-v41-code','deepseek-v3-report'],['modern-pretraining','long-context','inference-serving','agent-flywheel'])
model('kimi','Kimi · K3','Moonshot AI','本次核验代表：官方K3，非仅K2历史案例',['K2：公开Agentic合成与可验证反馈','K3：KDA、AttnRes与长上下文系统协同'],'把序列长度、深度信息流与专家容量当成三种不同的扩展轴。',['KDA/MLA混合与Attention Residuals分工不同','长上下文cooldown逐段扩展；不用把RoPE方案套给NoPE骨干','SFT、领域RL与多教师on-policy distillation串联'],['递归state怎样跨chunk、rank和prefix缓存保持一致？','AttnRes额外保存的深度状态如何影响流水线通信？'],'公开模型代码依赖外部kernel；完整pretraining/RL集群代码与数据未核验；自定义许可证需按分支阅读。',{**shared,'Open Weight':'是；官方模型卡与分片文件可确认','Open Source':'源码可见，但采用自定义许可证，不能等同通用开源授权','Inference Code':'modeling_kimi_k3.py / modeling_kimi_linear.py已核验','Technical Report':'官方GitHub固定commit PDF已核验','License':'Kimi K3 License；源码部分继承Apache-2.0'},['kimi-k3','kimi-k3-report','kimi-k3-code','kimi-k2-report'],['moe-training','long-context','posttraining','frontier-reading'])
model('qwen','Qwen · 3.8 Flash-Next / 27B','Qwen','本次核验代表：3.8 Flash-Next架构预览，同时对照3.8-27B',['Qwen3：分阶段预训练与推理能力塑形','Qwen3.8-27B：Dense GDN/Attention混合','Qwen3.8-Flash-Next：QSA、Gated Residual与n-gram embedding'],'同一个家族版本号仍可能包含不同架构和许可证。',['Flash-Next将稀疏选择推进到micro-block，并调节残差读写','按参数类型选择Muon/AdamW，重新拟合batch/LR','报告记录pretraining指标几乎无损、post-training生成变差的失败消融'],['gate是在时间维、残差维还是专家维起作用？','同名版本的Dense与MoE是否共享你想比较的变化？'],'Flash-Next被官方称为实验预览；27B不是同一架构；API Qwen3.8-Flash的托管功能不能自动归给权重checkpoint。',{**shared,'Open Weight':'两个所选分支均公开权重','Open Source':'27B与Flash-Next授权不同，不能按系列统一判断','Inference Code':'官方卡列Transformers/vLLM等兼容；此次未审计其全部实现','Technical Report':'Flash-Next官方GitHub固定commit PDF；27B模型卡','License':'27B: Apache-2.0；Flash-Next: Qwen Community License 1.0'},['qwen38','qwen38-report','qwen38-dense','qwen3-report'],['modern-pretraining','midtraining','training-stability','frontier-reading'])
model('glm','GLM · 5.3','Z.ai','本次核验代表：GLM-5.3官方公开权重',['GLM-5家族：Agentic Engineering研究','GLM-5.2→5.3：官方声明沿用同一base'],'提供一个将代际变化定位到后训练的清晰对照。',['同base声明使后训练增益成为主要研究问题','模型卡详细列harness、超时、sampling和benchmark修订'],['同一base上，数据、reward与rollout预算各贡献多少？','改过的评测任务与旧排行榜是否仍可直接比较？'],'5.3模型卡引用GLM-5家族报告；未公开的具体5.3训练配方不能由早期家族报告补全。',{**shared,'Open Weight':'是；官方HF权重分支','Open Source':'模型权重用自定义授权；推理框架另有各自许可证','Inference Code':'模型卡链接多种开源服务框架；本次HF仓库主要为权重/config','Technical Report':'可访问GLM-5家族报告；5.3全部增量细节未充分公开','License':'GLM-5.3 License（自定义）'},['glm53','glm5-report'],['posttraining','evaluation','frontier-reading'])
model('mimo','MiMo · V2.6-Flash-RL','Xiaomi MiMo','本次核验代表：2026-09-22可访问的V2.6公开RL分支',['V2.5→V2.6：官方同系列对照','V2.6：Agent中心mid-training与混合RL/分组评分'],'把中训练视为大批RL的能力、长度和优化器准备阶段。',['文本→全模态两阶段预训练，随后Agent中心中训练','中训练包含长度扩展、优化器适配和量化感知训练','GRS/GAR优化通过测试后的质量差异；后接MOPD2'],['中训练对后续RL的收益是否仍存在于固定rollout预算下？','组内质量排名是否引入grader偏好或新的reward hacking？'],'报告中的GRPO、grader和Muown设计没有在所下载modeling文件里完整实现；不要把推理定义当作训练源码。',{**shared,'Open Weight':'是；Flash-RL公开checkpoint','Open Source':'发布模型定义可读；完整训练系统的公开性未核验','Inference Code':'modeling_mimo_v2.py、configuration与draft定义','Technical Report':'固定HF SHA的完整PDF已核验','License':'模型卡标MIT；modeling_mimo_v2.py文件头Apache-2.0'},['mimo26','mimo26-report','mimo26-code'],['midtraining','capability-shaping','agent-rewards','reasoning-rl'])
model('gemma','Gemma · 4 12B Unified','Google DeepMind','本次核验海外代表：Gemma4公开系列中的12B Unified',['Gemma4家族：Dense/MoE及多种部署规模','Gemma4-12B Unified：encoder-free多模态分支'],'提供端侧效率与原生模态接口的另一种设计边界。',['12B分支直接处理图像/音频输入，区别于独立encoder路线','同家族包含预训练与指令checkpoint，以及不同Dense/MoE规模'],['多模态统一接口如何改变数据packing与算力分配？','端侧内存约束下，推理预算和训练目标怎样协同？'],'这一项用于机制对照，不声称它在所有任务优于更大模型；家族能力不能默认套在每个尺寸上。',{**shared,'Open Weight':'是；有base与instruction-tuned分支','Open Source':'官方模型许可证Apache-2.0；完整训练复现仍需单独核验','Inference Code':'官方提供多个运行生态；此次未逐个审计kernel','Technical Report':'Gemma4官方报告v2可访问','License':'Apache-2.0，已对照Google官方许可证页'},['gemma4','gemma4-report'],['modern-pretraining','inference-serving','frontier-reading'])
(ROOT/'src/data/sources-frontier.json').write_text(json.dumps(S,ensure_ascii=False,indent=2)+'\n');(ROOT/'src/data/models.json').write_text(json.dumps(M,ensure_ascii=False,indent=2)+'\n');print(len(S),'frontier sources;',len(M),'model families')
